const Router = require('express').Router;
const router = new Router();

router.get('/', (req, res) => {
  res.json({
    message: 'Welcome to Clash Royale API!',
    endpoints: {
		api: {
			arenas: 'api/arenas',
			cards: 'api/cards',
			chests: 'api/chests',
			players: 'api/players',
			leagues: 'api/leagues'
			},
		images: {
			arenas: 'images/arenas/{id}.png',
			cards: 'images/cards/{id}.png',
			chests: 'images/chests/{id}.png',
			emotions: 'images/emotions/{(angrer|cry|laugh|thumbs-up)}.gif',
			leagues: 'images/leagues/{id}.png',
			levels: 'images/levels/{level}.png',
			stats: 'images/stats/{stat}.png',
			ui: 'images/ui/{ui}.png'
		},
		stats: [
			'area-damage',
			'blank',
			'boost-rage',
			'charge-dash-damage',
			'common-level',
			'count',
			'crown-tower-damage',
			'damage',
			'dash-range',
			'death-damage',
			'deploy-time',
			'dps',
			'duration-lifetime',
			'elixer-cost',
			'epic-level',
			'healing',
			'hitpoints',
			'hit-speed',
			'legendary-level',
			'radius',
			'range',
			'rare-level',
			'shield-hitpoints',
			'slowdown-effect',
			'spawn-plus',
			'spawn',
			'speed',
			'stun-freeze',
			'target'
			],
		ui: [
			'add',
			'battle',
			'blue-crown',
			'cheer-blue',
			'cheer-red',
			'chest-reward',
			'clan-battle',
			'clan-battle-win',
			'common',
			'copy-deck',
			'cost',
			'crown-shield',
			'date',
			'deck',
			'draft',
			'epic',
			'gem-bucket',
			'gem',
			'gold',
			'gold-three',
			'icon',
			'king-tower',
			'leaderboard',
			'legendary',
			'legendary-trophy',
			'legendary-unknown',
			'level-big',
			'level-small',
			'locked',
			'logo',
			'log',
			'news',
			'no-cancel',
			'no-connection',
			'no-rewards',
			'pointing-hand',
			'random-deck',
			'random-unknown',
			'rank',
			'rare',
			'red-crown',
			'search',
			'settings',
			'shop-granpa-goblin',
			'shop',
			'social',
			'star',
			'tournament',
			'tourn-gold',
			'tourn-green',
			'training',
			'trophy',
			'tv-royale',
			'upgrade',
			'watch'
		]
    },
    version: '1.2.0',
    lastUpdate: 'March 21 2017',
  });
});

module.exports = router;
